In [1]:
import pandas as pd
import numpy as np
import xlrd
import matplotlib.pyplot as plt
%matplotlib inline

## Importing Data and Testing Files

In [2]:
htrain = pd.read_csv('F:/DATA SCIENCE/PROJECT 1 HOUSE PRICES/train.csv')
htest = pd.read_csv('F:/DATA SCIENCE/PROJECT 1 HOUSE PRICES/test.csv')

#The above code loads Data File(train) and Test File (test) into the Jupyter.

# Preparing Data File

In [3]:
h_train_num=htrain.select_dtypes(include=[np.number])
#Filters Numericals from the overall data
h_train_cat=htrain.select_dtypes(include=['object'])
#Filters Categorical/Words from the overall data

In [4]:
h_train_num.columns

Index(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd',
       'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
       'MiscVal', 'MoSold', 'YrSold', 'SalePrice'],
      dtype='object')

In [5]:
h_train_cat.columns

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='object')

In [6]:
for HC in h_train_num.columns:
    print (HC)
    print (h_train_num[HC].mean())
    print (h_train_num[HC].median())
    print('--------------------------------')
    
# Created a Data Frame 'HC'. Calculated mean and median of h_train_num and filled in HC
# in Ideal conditions, mean and medians are same in each case.

Id
730.5
730.5
--------------------------------
MSSubClass
56.897260274
50.0
--------------------------------
LotFrontage
70.049958368
69.0
--------------------------------
LotArea
10516.8280822
9478.5
--------------------------------
OverallQual
6.09931506849
6.0
--------------------------------
OverallCond
5.57534246575
5.0
--------------------------------
YearBuilt
1971.26780822
1973.0
--------------------------------
YearRemodAdd
1984.86575342
1994.0
--------------------------------
MasVnrArea
103.685261708
0.0
--------------------------------
BsmtFinSF1
443.639726027
383.5
--------------------------------
BsmtFinSF2
46.5493150685
0.0
--------------------------------
BsmtUnfSF
567.240410959
477.5
--------------------------------
TotalBsmtSF
1057.42945205
991.5
--------------------------------
1stFlrSF
1162.62671233
1087.0
--------------------------------
2ndFlrSF
346.992465753
0.0
--------------------------------
LowQualFinSF
5.84452054795
0.0
--------------------------------
GrLivArea
1515.46369863
1464.0
--------------------------------
BsmtFullBath
0.425342465753
0.0
--------------------------------
BsmtHalfBath
0.0575342465753
0.0
--------------------------------
FullBath
1.56506849315
2.0
--------------------------------
HalfBath
0.382876712329
0.0
--------------------------------
BedroomAbvGr
2.86643835616
3.0
--------------------------------
KitchenAbvGr
1.04657534247
1.0
--------------------------------
TotRmsAbvGrd
6.51780821918
6.0
--------------------------------
Fireplaces
0.61301369863
1.0
--------------------------------
GarageYrBlt
1978.50616389
1980.0
--------------------------------
GarageCars
1.76712328767
2.0
--------------------------------
GarageArea
472.980136986
480.0
--------------------------------
WoodDeckSF
94.2445205479
0.0
--------------------------------
OpenPorchSF
46.6602739726
25.0
--------------------------------
EnclosedPorch
21.954109589
0.0
--------------------------------
3SsnPorch
3.4095890411
0.0
--------------------------------
ScreenPorch
15.0609589041
0.0
--------------------------------
PoolArea
2.75890410959
0.0
--------------------------------
MiscVal
43.4890410959
0.0
--------------------------------
MoSold
6.32191780822
6.0
--------------------------------
YrSold
2007.81575342
2008.0
--------------------------------
SalePrice
180921.19589
163000.0
--------------------------------

In [7]:
h_train_num_corr=h_train_num.corr()
# Finds out co-relation between the columns in the data in order to find the important features

In [8]:
h_train_num_corr["SalePrice"]
# Gives the relation of Year Built wrt other columns

Id              -0.021917
MSSubClass      -0.084284
LotFrontage      0.351799
LotArea          0.263843
OverallQual      0.790982
OverallCond     -0.077856
YearBuilt        0.522897
YearRemodAdd     0.507101
MasVnrArea       0.477493
BsmtFinSF1       0.386420
BsmtFinSF2      -0.011378
BsmtUnfSF        0.214479
TotalBsmtSF      0.613581
1stFlrSF         0.605852
2ndFlrSF         0.319334
LowQualFinSF    -0.025606
GrLivArea        0.708624
BsmtFullBath     0.227122
BsmtHalfBath    -0.016844
FullBath         0.560664
HalfBath         0.284108
BedroomAbvGr     0.168213
KitchenAbvGr    -0.135907
TotRmsAbvGrd     0.533723
Fireplaces       0.466929
GarageYrBlt      0.486362
GarageCars       0.640409
GarageArea       0.623431
WoodDeckSF       0.324413
OpenPorchSF      0.315856
EnclosedPorch   -0.128578
3SsnPorch        0.044584
ScreenPorch      0.111447
PoolArea         0.092404
MiscVal         -0.021190
MoSold           0.046432
YrSold          -0.028923
SalePrice        1.000000
Name: SalePrice, dtype: float64

In [9]:
h_train_num_corr[(h_train_num_corr["SalePrice"]>0.35) ]
# Gives the complete data of relationships which are greater than 0.30

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
LotFrontage,-0.010601,-0.386347,1.000000,0.426095,0.251646,-0.059213,0.123349,0.088866,0.193458,0.233633,...,0.088521,0.151972,0.010700,0.070029,0.041383,0.206167,0.003368,0.011200,0.007450,0.351799
OverallQual,-0.028365,0.032628,0.251646,0.105806,1.000000,-0.091932,0.572323,0.550684,0.411876,0.239666,...,0.238923,0.308819,-0.113937,0.030371,0.064886,0.065166,-0.031406,0.070815,-0.027347,0.790982
YearBuilt,-0.012713,0.027850,0.123349,0.014228,0.572323,-0.375983,1.000000,0.592855,0.315707,0.249503,...,0.224880,0.188686,-0.387268,0.031355,-0.050364,0.004950,-0.034383,0.012398,-0.013618,0.522897
YearRemodAdd,-0.021998,0.040581,0.088866,0.013788,0.550684,0.073741,0.592855,1.000000,0.179618,0.128451,...,0.205726,0.226298,-0.193919,0.045286,-0.038740,0.005829,-0.010286,0.021490,0.035743,0.507101
MasVnrArea,-0.050298,0.022936,0.193458,0.104160,0.411876,-0.128101,0.315707,0.179618,1.000000,0.264736,...,0.159718,0.125703,-0.110204,0.018796,0.061466,0.011723,-0.029815,-0.005965,-0.008201,0.477493
BsmtFinSF1,-0.005024,-0.069836,0.233633,0.214103,0.239666,-0.046231,0.249503,0.128451,0.264736,1.000000,...,0.204306,0.111761,-0.102303,0.026451,0.062021,0.140491,0.003571,-0.015727,0.014359,0.386420
TotalBsmtSF,-0.015415,-0.238518,0.392075,0.260833,0.537808,-0.171098,0.391452,0.291066,0.363936,0.522396,...,0.232019,0.247264,-0.095478,0.037384,0.084489,0.126053,-0.018479,0.013196,-0.014969,0.613581
1stFlrSF,0.010496,-0.251758,0.457181,0.299475,0.476224,-0.144203,0.281986,0.240379,0.344501,0.445863,...,0.235459,0.211671,-0.065292,0.056104,0.088758,0.131525,-0.021096,0.031372,-0.013604,0.605852
GrLivArea,0.008273,0.074853,0.402797,0.263116,0.593007,-0.079686,0.199010,0.287389,0.390857,0.208171,...,0.247433,0.330224,0.009113,0.020643,0.101510,0.170205,-0.002416,0.050240,-0.036526,0.708624
FullBath,0.005587,0.131608,0.198769,0.126031,0.550600,-0.194149,0.468271,0.439046,0.276833,0.058543,...,0.187703,0.259977,-0.115093,0.035353,-0.008106,0.049604,-0.014290,0.055872,-0.019669,0.560664
TotRmsAbvGrd,0.027239,0.040380,0.352096,0.190015,0.427452,-0.057583,0.095589,0.191740,0.280682,0.044316,...,0.165984,0.234192,0.004151,-0.006683,0.059383,0.083757,0.024763,0.036907,-0.034516,0.533723
Fireplaces,-0.019772,-0.045569,0.266639,0.271364,0.396765,-0.023820,0.147716,0.112581,0.249070,0.260011,...,0.200019,0.169405,-0.024822,0.011257,0.184530,0.095074,0.001409,0.046357,-0.024096,0.466929
GarageYrBlt,0.000072,0.085072,0.070250,-0.024947,0.547766,-0.324297,0.825667,0.642277,0.252691,0.153484,...,0.224577,0.228425,-0.297003,0.023544,-0.075418,-0.014501,-0.032417,0.005337,-0.001014,0.486362
GarageCars,0.016570,-0.040110,0.285691,0.154871,0.600671,-0.185758,0.537850,0.420622,0.364204,0.224054,...,0.226342,0.213569,-0.151434,0.035765,0.050494,0.020934,-0.043080,0.040522,-0.039117,0.640409
GarageArea,0.017634,-0.098672,0.344997,0.180403,0.562022,-0.151521,0.478954,0.371600,0.373066,0.296970,...,0.224666,0.241435,-0.121777,0.035087,0.051412,0.061047,-0.027400,0.027974,-0.027378,0.623431
SalePrice,-0.021917,-0.084284,0.351799,0.263843,0.790982,-0.077856,0.522897,0.507101,0.477493,0.386420,...,0.324413,0.315856,-0.128578,0.044584,0.111447,0.092404,-0.021190,0.046432,-0.028923,1.000000

In [10]:
h_train_num_corr[(h_train_num_corr["SalePrice"]<-0.35) ]
# Gives the complete data of relationships which are less than 0.3 (its our wish), Usually it is between 0.3 to 0.6

Empty DataFrame
Columns: [Id, MSSubClass, LotFrontage, LotArea, OverallQual, OverallCond, YearBuilt, YearRemodAdd, MasVnrArea, BsmtFinSF1, BsmtFinSF2, BsmtUnfSF, TotalBsmtSF, 1stFlrSF, 2ndFlrSF, LowQualFinSF, GrLivArea, BsmtFullBath, BsmtHalfBath, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, TotRmsAbvGrd, Fireplaces, GarageYrBlt, GarageCars, GarageArea, WoodDeckSF, OpenPorchSF, EnclosedPorch, 3SsnPorch, ScreenPorch, PoolArea, MiscVal, MoSold, YrSold, SalePrice]
Index: []

[0 rows x 38 columns]

In [11]:
h_train_num_corr[(h_train_num_corr["SalePrice"]>0.35) ].index.values
# This gives the details of those columns which have the co-relation value between -1 to 0.35 and 0.35 to 1

array(['LotFrontage', 'OverallQual', 'YearBuilt', 'YearRemodAdd',
       'MasVnrArea', 'BsmtFinSF1', 'TotalBsmtSF', '1stFlrSF', 'GrLivArea',
       'FullBath', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt',
       'GarageCars', 'GarageArea', 'SalePrice'], dtype=object)

In [12]:
h_train_num_corr[(h_train_num_corr["SalePrice"]<-0.35) ].index.values
# To choose columns whose relationship lies between -1 to -0.35 (unfortunately there are no outputs)

array([], dtype=object)

In [13]:
h_train_num_cols = []
h_train_num_cols.extend(h_train_num_corr[(h_train_num_corr["SalePrice"]>0.35) ].index.values)
h_train_num_cols.extend(h_train_num_corr[(h_train_num_corr["SalePrice"]<-0.35) ].index.values)

# Created a Data Frame h_train_num_cols and imported values of sales price relations

In [14]:
h_train_num_cols

['LotFrontage',
 'OverallQual',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'BsmtFinSF1',
 'TotalBsmtSF',
 '1stFlrSF',
 'GrLivArea',
 'FullBath',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea',
 'SalePrice']

In [15]:
h_train_num_col_filtered=h_train_num[h_train_num_cols]

# From overall data( i.e. h_train_num) we are choosing only those columns which are effecting more(i.e. h_train_num_cols) as per the correlation resuts

In [16]:
h_train_num_col_filtered

,LotFrontage,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,SalePrice
0,65.0,7,2003,2003,196.0,706,856,856,1710,2,8,0,2003.0,2,548,208500
1,80.0,6,1976,1976,0.0,978,1262,1262,1262,2,6,1,1976.0,2,460,181500
2,68.0,7,2001,2002,162.0,486,920,920,1786,2,6,1,2001.0,2,608,223500
3,60.0,7,1915,1970,0.0,216,756,961,1717,1,7,1,1998.0,3,642,140000
4,84.0,8,2000,2000,350.0,655,1145,1145,2198,2,9,1,2000.0,3,836,250000
5,85.0,5,1993,1995,0.0,732,796,796,1362,1,5,0,1993.0,2,480,143000
6,75.0,8,2004,2005,186.0,1369,1686,1694,1694,2,7,1,2004.0,2,636,307000
7,NaN,7,1973,1973,240.0,859,1107,1107,2090,2,7,2,1973.0,2,484,200000
8,51.0,7,1931,1950,0.0,0,952,1022,1774,2,8,2,1931.0,2,468,129900
9,50.0,5,1939,1950,0.0,851,991,1077,1077,1,5,2,1939.0,1,205,118000
10,70.0,5,1965,1965,0.0,906,1040,1040,1040,1,5,0,1965.0,1,384,129500
11,85.0,9,2005,2006,286.0,998,1175,1182,2324,3,11,2,2005.0,3,736,345000
12,NaN,5,1962,1962,0.0,737,912,912,912,1,4,0,1962.0,1,352,144000
13,91.0,7,2006,2007,306.0,0,1494,1494,1494,2,7,1,2006.0,3,840,279500
14,NaN,6,1960,1960,212.0,733,1253,1253,1253,1,5,1,1960.0,1,352,157000
15,51.0,7,1929,2001,0.0,0,832,854,854,1,5,0,1991.0,2,576,132000
16,NaN,6,1970,1970,180.0,578,1004,1004,1004,1,5,1,1970.0,2,480,149000
17,72.0,4,1967,1967,0.0,0,0,1296,1296,2,6,0,1967.0,2,516,90000
18,66.0,5,2004,2004,0.0,646,1114,1114,1114,1,6,0,2004.0,2,576,159000
19,70.0,5,1958,1965,0.0,504,1029,1339,1339,1,6,0,1958.0,1,294,139000
20,101.0,8,2005,2006,380.0,0,1158,1158,2376,3,9,1,2005.0,3,853,325300
21,57.0,7,1930,1950,0.0,0,637,1108,1108,1,6,1,1930.0,1,280,139400
22,75.0,8,2002,2002,281.0,0,1777,1795,1795,2,7,1,2002.0,2,534,230000
23,44.0,5,1976,1976,0.0,840,1040,1060,1060,1,6,1,1976.0,2,572,129900
24,NaN,5,1968,2001,0.0,188,1060,1060,1060,1,6,1,1968.0,1,270,154000
25,110.0,8,2007,2007,640.0,0,1566,1600,1600,2,7,1,2007.0,3,890,256300
26,60.0,5,1951,2000,0.0,234,900,900,900,1,5,0,2005.0,2,576,134800
27,98.0,8,2007,2008,200.0,1218,1704,1704,1704,2,7,1,2008.0,3,772,306000
28,47.0,5,1957,1997,0.0,1277,1484,1600,1600,1,6,2,1957.0,1,319,207500
29,60.0,4,1927,1950,0.0,0,520,520,520,1,4,0,1920.0,1,240,68500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,60.0,5,2005,2005,0.0,0,732,734,1838,2,7,1,2005.0,2,372,192140
1431,NaN,6,1976,1976,0.0,958,958,958,958,2,5,0,1976.0,2,440,143750
1432,60.0,4,1927,2007,0.0,0,656,968,968,2,5,0,1928.0,1,216,64500
1433,93.0,6,2000,2000,318.0,0,936,962,1792,2,8,1,2000.0,2,451,186500
1434,80.0,5,1977,1977,0.0,936,1126,1126,1126,2,5,1,1977.0,2,484,160000
1435,80.0,6,1962,2005,237.0,0,1319,1537,1537,1,7,1,1962.0,2,462,174000
1436,60.0,4,1971,1971,0.0,616,864,864,864,1,5,0,1974.0,2,528,120500
1437,96.0,8,2008,2008,426.0,1336,1932,1932,1932,2,7,1,2008.0,3,774,394617
1438,90.0,6,1957,1996,0.0,600,912,1236,1236,1,6,0,1957.0,2,923,149700
1439,80.0,7,1979,1979,96.0,315,539,1040,1725,2,6,1,1979.0,2,550,197000
1440,79.0,6,1922,1994,0.0,0,588,1423,2555,2,11,1,1993.0,2,672,191000
1441,NaN,6,2004,2004,147.0,697,848,848,848,1,3,1,2004.0,2,420,149300
1442,85.0,10,2008,2008,160.0,765,1017,1026,2007,2,10,1,2008.0,3,812,310000
1443,NaN,6,1916,1950,0.0,0,952,952,952,1,4,1,1916.0,1,192,121000
1444,63.0,7,2004,2004,106.0,0,1422,1422,1422,2,7,0,2004.0,2,626,179600
1445,70.0,6,1966,1966,0.0,187,814,913,913,1,6,0,1990.0,1,240,129000
1446,NaN,5,1962,1962,189.0,593,1188,1188,1188,1,6,0,1962.0,1,312,157900
1447,80.0,8,1995,1996,438.0,1079,1220,1220,2090,2,8,1,1995.0,2,556,240000
1448,70.0,4,1910,2000,0.0,0,560,796,1346,1,6,0,1950.0,1,384,112000
1449,21.0,5,1970,1970,0.0,553,630,630,630,1,3,0,NaN,0,0,92000
1450,60.0,5,1974,1974,0.0,0,896,896,1792,2,8,0,NaN,0,0,136000
1451,78.0,8,2008,2009,194.0,0,1573,1578,1578,2,7,1,2008.0,3,840,287090
1452,35.0,5,2005,2005,80.0,547,547,1072,1072,1,5,0,2005.0,2,525,145000
1453,90.0,5,2006,2006,0.0,0,1140,1140,1140,1,6,0,NaN,0,0,84500
1454,62.0,7,2004,2005,0.0,410,1221,1221,1221,2,6,0,2004.0,2,400,185000
1455,62.0,6,1999,2000,0.0,0,953,953,1647,2,7,1,1999.0,2,460,175000
1456,85.0,6,1978,1988,119.0,790,1542,2073,2073,2,7,2,1978.0,2,500,210000
1457,66.0,7,1941,2006,0.0,275,1152,1188,2340,2,9,2,1941.0,1,252,266500
1458,68.0,5,1950,1996,0.0,49,1078,1078,1078,1,5,0,1950.0,1,240,142125
1459,75.0,5,1965,1965,0.0,830,1256,1256,1256,1,6,0,1965.0,1,276,147500

In [17]:
(h_train_num_col_filtered.isnull().sum().sort_values(ascending=False))
# Finding the empty cells

LotFrontage     259
GarageYrBlt      81
MasVnrArea        8
SalePrice         0
GarageArea        0
GarageCars        0
Fireplaces        0
TotRmsAbvGrd      0
FullBath          0
GrLivArea         0
1stFlrSF          0
TotalBsmtSF       0
BsmtFinSF1        0
YearRemodAdd      0
YearBuilt         0
OverallQual       0
dtype: int64

In [18]:
for col in ["LotFrontage","GarageYrBlt","MasVnrArea"]:
    h_train_num_col_filtered[col].fillna(h_train_num_col_filtered[col].median(),inplace=True)
    # This step fills Nans with median value

C:\Users\prana\AppData\Local\conda\conda\envs\tfdeeplearning\lib\site-packages\pandas\core\generic.py:3660: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
le=LabelEncoder()
# Fro here we start working on categoricals

In [21]:
h_train_cat.head()

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1,RL,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
2,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
3,RL,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,...,Detchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Abnorml
4,RL,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal

In [22]:
(h_train_cat.isnull().sum().sort_values(ascending=False))
#To find out NaNs in the categoricals

PoolQC           1453
MiscFeature      1406
Alley            1369
Fence            1179
FireplaceQu       690
GarageCond         81
GarageQual         81
GarageFinish       81
GarageType         81
BsmtFinType2       38
BsmtExposure       38
BsmtFinType1       37
BsmtQual           37
BsmtCond           37
MasVnrType          8
Electrical          1
Condition2          0
Condition1          0
Neighborhood        0
LandSlope           0
BldgType            0
LandContour         0
LotConfig           0
Utilities           0
RoofStyle           0
LotShape            0
Street              0
HouseStyle          0
SaleCondition       0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
ExterQual           0
ExterCond           0
Foundation          0
SaleType            0
Heating             0
HeatingQC           0
CentralAir          0
KitchenQual         0
Functional          0
PavedDrive          0
MSZoning            0
dtype: int64

In [23]:
for col in ["PoolQC","MiscFeature","Alley","Fence","FireplaceQu"]:
    h_train_cat[col].fillna('No Value',inplace=True)
# Here we are filling NaNs in "PoolQC","MiscFeature","Alley","Fence","FireplaceQu" with No Value Since more than half data is missing

C:\Users\prana\AppData\Local\conda\conda\envs\tfdeeplearning\lib\site-packages\pandas\core\generic.py:3660: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [24]:
for col in ["GarageCond","GarageQual","GarageFinish","GarageType","BsmtFinType2","BsmtExposure","BsmtFinType1","BsmtQual","BsmtCond","MasVnrType","Electrical"]:
    h_train_cat[col].fillna(h_train_cat[col].value_counts().idxmax(),inplace=True)
    # This step is to fill the NaNs with Mode values

C:\Users\prana\AppData\Local\conda\conda\envs\tfdeeplearning\lib\site-packages\pandas\core\generic.py:3660: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [25]:
h_train_cat.head()

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,RL,Pave,No Value,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,No Value,No Value,No Value,WD,Normal
1,RL,Pave,No Value,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,...,Attchd,RFn,TA,TA,Y,No Value,No Value,No Value,WD,Normal
2,RL,Pave,No Value,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,No Value,No Value,No Value,WD,Normal
3,RL,Pave,No Value,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,...,Detchd,Unf,TA,TA,Y,No Value,No Value,No Value,WD,Abnorml
4,RL,Pave,No Value,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,...,Attchd,RFn,TA,TA,Y,No Value,No Value,No Value,WD,Normal

In [26]:
h_train_cat1=h_train_cat.apply(le.fit_transform)
# This steps encodes the words with a code(numerical)

In [27]:
h_train_cat1.head()

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,3,1,1,3,3,0,4,0,5,2,...,1,1,4,4,2,3,4,1,8,4
1,3,1,1,3,3,0,2,0,24,1,...,1,1,4,4,2,3,4,1,8,4
2,3,1,1,0,3,0,4,0,5,2,...,1,1,4,4,2,3,4,1,8,4
3,3,1,1,0,3,0,0,0,6,2,...,5,2,4,4,2,3,4,1,8,0
4,3,1,1,0,3,0,2,0,15,2,...,1,1,4,4,2,3,4,1,8,4

In [28]:
TrainingDATA=pd.concat([h_train_num_col_filtered,h_train_cat1],axis=1)

In [29]:
TrainingDATA.head()

,LotFrontage,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,65.0,7,2003,2003,196.0,706,856,856,1710,2,...,1,1,4,4,2,3,4,1,8,4
1,80.0,6,1976,1976,0.0,978,1262,1262,1262,2,...,1,1,4,4,2,3,4,1,8,4
2,68.0,7,2001,2002,162.0,486,920,920,1786,2,...,1,1,4,4,2,3,4,1,8,4
3,60.0,7,1915,1970,0.0,216,756,961,1717,1,...,5,2,4,4,2,3,4,1,8,0
4,84.0,8,2000,2000,350.0,655,1145,1145,2198,2,...,1,1,4,4,2,3,4,1,8,4

## Preparing Test Data File

In [30]:
h_test_num=htest.select_dtypes(include=[np.number])
#Filters Numericals from the overall data

h_test_cat=htest.select_dtypes(include=['object'])
#Filters Categorical/Words from the overall data

In [31]:
h_train_num_cols.remove('SalePrice')
# Removes SalePrice from Training Data and Keeps the remaining Data COlumns
# Note: The Data thats is in Training should be in Testing as well

In [32]:
h_test_num_col_filtered=h_test_num[h_train_num_cols]

In [33]:
(h_test_num_col_filtered.isnull().sum().sort_values(ascending=False))
# Finding the Nans

LotFrontage     227
GarageYrBlt      78
MasVnrArea       15
GarageArea        1
GarageCars        1
TotalBsmtSF       1
BsmtFinSF1        1
Fireplaces        0
TotRmsAbvGrd      0
FullBath          0
GrLivArea         0
1stFlrSF          0
YearRemodAdd      0
YearBuilt         0
OverallQual       0
dtype: int64

In [34]:
for hc in ["LotFrontage","GarageYrBlt","MasVnrArea","TotalBsmtSF","GarageArea","GarageCars","BsmtFinSF1"]:
    print (hc)
    print(h_test_num_col_filtered[hc].mean())
    print(h_test_num_col_filtered[hc].median())
    print ("------------------------------")

LotFrontage
68.5803571429
67.0
------------------------------
GarageYrBlt
1977.72121651
1979.0
------------------------------
MasVnrArea
100.709141274
0.0
------------------------------
TotalBsmtSF
1046.11796982
988.0
------------------------------
GarageArea
472.768861454
480.0
------------------------------
GarageCars
1.76611796982
2.0
------------------------------
BsmtFinSF1
439.203703704
350.5
------------------------------

In [35]:
for col in ["LotFrontage","GarageYrBlt","MasVnrArea","TotalBsmtSF","GarageArea","GarageCars","BsmtFinSF1"]:
    h_test_num_col_filtered[col].fillna(h_test_num_col_filtered[col].median(),inplace=True)

C:\Users\prana\AppData\Local\conda\conda\envs\tfdeeplearning\lib\site-packages\pandas\core\generic.py:3660: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [36]:
(h_test_cat.isnull().sum().sort_values(ascending=False))
# Fining the NaNs in Categoricals

PoolQC           1456
MiscFeature      1408
Alley            1352
Fence            1169
FireplaceQu       730
GarageCond         78
GarageQual         78
GarageFinish       78
GarageType         76
BsmtCond           45
BsmtQual           44
BsmtExposure       44
BsmtFinType2       42
BsmtFinType1       42
MasVnrType         16
MSZoning            4
Utilities           2
Functional          2
KitchenQual         1
SaleType            1
Exterior2nd         1
Exterior1st         1
Heating             0
Condition2          0
Street              0
PavedDrive          0
LotShape            0
LandContour         0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
RoofStyle           0
BldgType            0
HouseStyle          0
HeatingQC           0
RoofMatl            0
ExterQual           0
ExterCond           0
Foundation          0
Electrical          0
CentralAir          0
SaleCondition       0
dtype: int64

In [37]:
for col in ["PoolQC","MiscFeature","Alley","Fence","FireplaceQu"]:
    h_test_cat[col].fillna('No Value',inplace=True)

C:\Users\prana\AppData\Local\conda\conda\envs\tfdeeplearning\lib\site-packages\pandas\core\generic.py:3660: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [38]:
for col in ["GarageCond","GarageQual","GarageFinish","GarageType","BsmtQual","BsmtCond","BsmtFinType2","BsmtExposure","BsmtFinType1","MasVnrType","MSZoning","Utilities","Functional","KitchenQual","SaleType","Exterior2nd","Exterior1st"]:
    h_test_cat[col].fillna(h_test_cat[col].value_counts().idxmax(),inplace=True)

C:\Users\prana\AppData\Local\conda\conda\envs\tfdeeplearning\lib\site-packages\pandas\core\generic.py:3660: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [39]:
h_test_cat1=h_test_cat.apply(le.fit_transform)

In [40]:
TestingDATA=pd.concat([h_test_num_col_filtered,h_test_cat1],axis=1)

In [41]:
TestingDATA.head()

,LotFrontage,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,80.0,5,1961,1961,0.0,468.0,882.0,896,896,1,...,1,2,3,4,2,2,2,1,8,4
1,81.0,6,1958,1958,108.0,923.0,1329.0,1329,1329,1,...,1,2,3,4,2,2,4,0,8,4
2,74.0,5,1997,1998,0.0,791.0,928.0,928,1629,2,...,1,0,3,4,2,2,2,1,8,4
3,78.0,6,1998,1998,20.0,602.0,926.0,926,1604,2,...,1,0,3,4,2,2,4,1,8,4
4,43.0,8,1992,1992,0.0,263.0,1280.0,1280,1280,2,...,1,1,3,4,2,2,4,1,8,4

# Splitting Train File into Training Dataset and Testing Dataset to Build Models

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
XX=TrainingDATA.drop(["SalePrice"],axis=1)

In [44]:
YY=TrainingDATA["SalePrice"]

In [45]:
X_train, X_test, y_train, y_test = train_test_split(XX, YY, test_size=0.3)

#X_Train will consist of 70% data and X Test will Consist of 30% data for Testing
# X = all the columns except output(Salesprice)
# Y = only SalesPrice that has to be predicted

In [46]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1022, 58)
(438, 58)
(1022,)
(438,)

# LINEAR REGRESSION MODEL SCORE

In [47]:
from sklearn.linear_model import LinearRegression

In [48]:
Linreg=LinearRegression()

In [49]:
lm_M=Linreg.fit(X_train,y_train)

In [50]:
lm_M.score(X_train,y_train)

0.85738327254107116

# DECISION TREE REGRESSION MODEL SCORE

In [51]:
from sklearn.tree import DecisionTreeRegressor

In [52]:
DecTree=DecisionTreeRegressor()

In [53]:
dt_M=DecTree.fit(X_train,y_train)

In [54]:
dt_M.score(X_train,y_train)

1.0

# RANDOM FOREST REGRESSION MODEL SCORE

In [55]:
from sklearn.ensemble import RandomForestRegressor

In [56]:
RandFor=RandomForestRegressor(n_estimators=5000)

In [57]:
rf_M=RandFor.fit(X_train,y_train)

In [58]:
rf_M.score(X_train,y_train)

0.97947729792006466

# GRADIENT BOOST REGRESSION MODEL

In [59]:
from sklearn.ensemble import GradientBoostingRegressor

In [60]:
GBM=GradientBoostingRegressor(n_estimators=3000)

In [61]:
gb_M=GBM.fit(X_train,y_train)

In [62]:
gb_M.score(X_train,y_train)

0.99998567025224816

# TEST SCORES OF MODELS BUILT

In [63]:
from sklearn.metrics import accuracy_score, r2_score

In [64]:
gb_y_pred = gb_M.predict(X_test)
rf_y_pred = rf_M.predict(X_test)
dt_y_pred = dt_M.predict(X_test)
lm_y_pred = lm_M.predict(X_test)

In [65]:
r2_score(y_test,gb_y_pred)

0.88469711783475169

In [66]:
r2_score(y_test,rf_y_pred)

0.85954990241205398

In [67]:
r2_score(y_test,dt_y_pred)

0.66965688911960508

In [68]:
r2_score(y_test,lm_y_pred)

0.7625202434330467

# Since the r2_score of Gradient Boost is better than other algorithms, the  actual Testing File is now executed using Graident model to predict the Sales Price.

In [69]:
y_eval=gb_M.predict(TestingDATA)
# Predicts the SalesPrice

In [70]:
pd.DataFrame(y_eval).to_csv('GB.csv')
# Saves the Predcted Values as GB.csv file in your PC